name: Setup ansible

description: Setup ansible for VM

inputs:
  ssh_private_key:
    description: 'SSH Private key, base64 encoded'
    required: true
  known_hosts:
    description: 'Known hosts info'
    required: true
  vm_host:
    description: 'VM address'
    required: true
  vm_user:
    description: 'VM user'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v4
  
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.13'
  
  - name: Install Ansible
    shell: bash
    run: pipx install --include-deps ansible ansible-lint
  
  - name: Install Ansible collections
    shell: bash
    run: ansible-galaxy collection install -r requirements.yml
  
  - name: Set up SSH
    shell: bash
    run: |
      eval `ssh-agent -s`
      mkdir -p ~/.ssh/
      touch ~/.ssh/id_ed25519
      echo -e "${{ inputs.ssh_private_key }}" | base64 -d | tr -d '\r' > ~/.ssh/id_ed25519
      chmod 700 ~/.ssh/id_ed25519
      echo -e "${{ inputs.known_hosts }}" >> ~/.ssh/known_hosts

  - name: Create inventory
    shell: bash
    run: |
      cat > ansible/inventory.ini << EOF
      [vms]
      ${{ inputs.vm_host }} ansible_user=${{ inputs.vm_user }}
      EOF

  - name: Get changed files
    id: changed-files
    uses: tj-actions/changed-files@main
    with:
      files: |
        ansible/playbooks/**
  
  - name: Lint playbooks
    shell: bash
    if: steps.changed-files.outputs.any_changed == 'true'
    run: ansible-lint ansible/playbooks