// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost' | 'https://vet-clinic.itis-sel.com' | (string & {});
};

/**
 * AuthTokenData
 */
export type AuthTokenData = {
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Type
     */
    type?: string;
};

/**
 * Body_login_api_v1_auth_login_post
 */
export type BodyLoginApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChangePasswordData
 */
export type ChangePasswordData = {
    /**
     * Verification Code
     */
    verification_code: string;
};

/**
 * ForbiddenErrorSchema
 */
export type ForbiddenErrorSchema = {
    /**
     * Detail
     */
    detail?: {
        [key: string]: unknown;
    } | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InternalServerErrorSchema
 */
export type InternalServerErrorSchema = {
    /**
     * Detail
     */
    detail?: {
        [key: string]: unknown;
    } | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * ListResponse[PermissionPublic]
 */
export type ListResponsePermissionPublic = {
    info: PaginationInfo;
    /**
     * Items
     */
    items: Array<PermissionPublic>;
};

/**
 * ListResponse[RolePublic]
 */
export type ListResponseRolePublic = {
    info: PaginationInfo;
    /**
     * Items
     */
    items: Array<RolePublic>;
};

/**
 * ListResponse[UserPublic]
 */
export type ListResponseUserPublic = {
    info: PaginationInfo;
    /**
     * Items
     */
    items: Array<UserPublic>;
};

/**
 * LoginErrorSchema
 */
export type LoginErrorSchema = {
    /**
     * Detail
     */
    detail?: null;
    /**
     * Message
     */
    message?: string;
};

/**
 * NotFoundErrorSchema
 */
export type NotFoundErrorSchema = {
    /**
     * Detail
     */
    detail?: {
        [key: string]: unknown;
    } | null;
    /**
     * Message
     */
    message?: string;
};

/**
 * OkSchema
 */
export type OkSchema = {
    /**
     * Message
     */
    message?: string;
};

/**
 * PaginationInfo
 */
export type PaginationInfo = {
    /**
     * Page
     */
    page: number;
    /**
     * Pages Num
     */
    pages_num: number;
    /**
     * Total
     */
    total: number;
};

/**
 * PermissionCreate
 */
export type PermissionCreate = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Action
     */
    action: string;
};

/**
 * PermissionPublic
 */
export type PermissionPublic = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Action
     */
    action: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Alias
     */
    readonly alias: string;
};

/**
 * PetModel
 */
export type PetModel = {
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Name
     */
    name: string;
    type?: PetType;
    /**
     * Owner Id
     */
    owner_id?: string;
};

/**
 * PetType
 */
export type PetType = 'cat' | 'dog' | 'parrot';

/**
 * RegisterErrorSchema
 */
export type RegisterErrorSchema = {
    /**
     * Detail
     */
    detail?: null;
    /**
     * Message
     */
    message?: string;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Scope Aliases
     */
    scope_aliases?: Array<string>;
};

/**
 * RolePublic
 */
export type RolePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Scopes
     */
    readonly scopes: Array<string>;
};

/**
 * UnauthorizedErrorSchema
 */
export type UnauthorizedErrorSchema = {
    /**
     * Detail
     */
    detail?: null;
    /**
     * Message
     */
    message?: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
    /**
     * Role Id
     */
    role_id: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * UserStatus
 */
export type UserStatus = 'created' | 'confirmed' | 'banned';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Username
     */
    username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ChangePasswordData
 */
export type ChangePasswordDataWritable = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
    /**
     * Verification Code
     */
    verification_code: string;
};

/**
 * ListResponse[PermissionPublic]
 */
export type ListResponsePermissionPublicWritable = {
    info: PaginationInfo;
    /**
     * Items
     */
    items: Array<PermissionPublicWritable>;
};

/**
 * ListResponse[RolePublic]
 */
export type ListResponseRolePublicWritable = {
    info: PaginationInfo;
    /**
     * Items
     */
    items: Array<RolePublicWritable>;
};

/**
 * PermissionPublic
 */
export type PermissionPublicWritable = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Action
     */
    action: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * RolePublic
 */
export type RolePublicWritable = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

export type GetProfileApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetProfileApiV1UsersMeGetErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type GetProfileApiV1UsersMeGetError = GetProfileApiV1UsersMeGetErrors[keyof GetProfileApiV1UsersMeGetErrors];

export type GetProfileApiV1UsersMeGetResponses = {
    /**
     * Response Get Profile Api V1 Users Me Get
     *
     * Successful Response
     */
    200: UserPublic | null;
};

export type GetProfileApiV1UsersMeGetResponse = GetProfileApiV1UsersMeGetResponses[keyof GetProfileApiV1UsersMeGetResponses];

export type GetUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * First Name
         */
        first_name?: string | null;
        /**
         * Last Name
         */
        last_name?: string | null;
        /**
         * Status
         */
        status?: UserStatus | null;
        /**
         * Email
         */
        email?: string | null;
        /**
         * Username
         */
        username?: string | null;
    };
    url: '/api/v1/users/';
};

export type GetUsersApiV1UsersGetErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type GetUsersApiV1UsersGetError = GetUsersApiV1UsersGetErrors[keyof GetUsersApiV1UsersGetErrors];

export type GetUsersApiV1UsersGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseUserPublic;
};

export type GetUsersApiV1UsersGetResponse = GetUsersApiV1UsersGetResponses[keyof GetUsersApiV1UsersGetResponses];

export type DeleteUserApiV1UsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserApiV1UsersUserIdDeleteErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type DeleteUserApiV1UsersUserIdDeleteError = DeleteUserApiV1UsersUserIdDeleteErrors[keyof DeleteUserApiV1UsersUserIdDeleteErrors];

export type DeleteUserApiV1UsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type DeleteUserApiV1UsersUserIdDeleteResponse = DeleteUserApiV1UsersUserIdDeleteResponses[keyof DeleteUserApiV1UsersUserIdDeleteResponses];

export type GetUserApiV1UsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type GetUserApiV1UsersUserIdGetErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Not Found
     */
    404: NotFoundErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type GetUserApiV1UsersUserIdGetError = GetUserApiV1UsersUserIdGetErrors[keyof GetUserApiV1UsersUserIdGetErrors];

export type GetUserApiV1UsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetUserApiV1UsersUserIdGetResponse = GetUserApiV1UsersUserIdGetResponses[keyof GetUserApiV1UsersUserIdGetResponses];

export type UpdateUserApiV1UsersUserIdPutData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserApiV1UsersUserIdPutErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type UpdateUserApiV1UsersUserIdPutError = UpdateUserApiV1UsersUserIdPutErrors[keyof UpdateUserApiV1UsersUserIdPutErrors];

export type UpdateUserApiV1UsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserApiV1UsersUserIdPutResponse = UpdateUserApiV1UsersUserIdPutResponses[keyof UpdateUserApiV1UsersUserIdPutResponses];

export type GetUserPetsApiV1UsersUserIdPetsGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/pets';
};

export type GetUserPetsApiV1UsersUserIdPetsGetErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type GetUserPetsApiV1UsersUserIdPetsGetError = GetUserPetsApiV1UsersUserIdPetsGetErrors[keyof GetUserPetsApiV1UsersUserIdPetsGetErrors];

export type GetUserPetsApiV1UsersUserIdPetsGetResponses = {
    /**
     * Response Get User Pets Api V1 Users  User Id  Pets Get
     *
     * Successful Response
     */
    200: Array<PetModel>;
};

export type GetUserPetsApiV1UsersUserIdPetsGetResponse = GetUserPetsApiV1UsersUserIdPetsGetResponses[keyof GetUserPetsApiV1UsersUserIdPetsGetResponses];

export type GetPetsApiV1PetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Name
         */
        name?: string | null;
    };
    url: '/api/v1/pets/';
};

export type GetPetsApiV1PetsGetErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type GetPetsApiV1PetsGetError = GetPetsApiV1PetsGetErrors[keyof GetPetsApiV1PetsGetErrors];

export type GetPetsApiV1PetsGetResponses = {
    /**
     * Response Get Pets Api V1 Pets  Get
     *
     * Successful Response
     */
    200: Array<PetModel>;
};

export type GetPetsApiV1PetsGetResponse = GetPetsApiV1PetsGetResponses[keyof GetPetsApiV1PetsGetResponses];

export type CreatePetsApiV1PetsPostData = {
    body: PetModel;
    path?: never;
    query?: never;
    url: '/api/v1/pets/';
};

export type CreatePetsApiV1PetsPostErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type CreatePetsApiV1PetsPostError = CreatePetsApiV1PetsPostErrors[keyof CreatePetsApiV1PetsPostErrors];

export type CreatePetsApiV1PetsPostResponses = {
    /**
     * Successful Response
     */
    200: PetModel;
};

export type CreatePetsApiV1PetsPostResponse = CreatePetsApiV1PetsPostResponses[keyof CreatePetsApiV1PetsPostResponses];

export type LoginApiV1AuthLoginPostData = {
    body: BodyLoginApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Unauthorized
     */
    401: LoginErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Response Login Api V1 Auth Login Post
     *
     * Successful Response
     */
    200: AuthTokenData | null;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type RefreshApiV1AuthRefreshPostError = RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * Response Refresh Api V1 Auth Refresh Post
     *
     * Successful Response
     */
    200: AuthTokenData | null;
};

export type RefreshApiV1AuthRefreshPostResponse = RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type LogoutApiV1AuthLogoutDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutDeleteErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type LogoutApiV1AuthLogoutDeleteError = LogoutApiV1AuthLogoutDeleteErrors[keyof LogoutApiV1AuthLogoutDeleteErrors];

export type LogoutApiV1AuthLogoutDeleteResponses = {
    /**
     * Successful Response
     */
    200: OkSchema;
};

export type LogoutApiV1AuthLogoutDeleteResponse = LogoutApiV1AuthLogoutDeleteResponses[keyof LogoutApiV1AuthLogoutDeleteResponses];

export type RegisterApiV1AuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
    /**
     * Conflict
     */
    409: RegisterErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type RegisterApiV1AuthRegisterPostError = RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyAccountApiV1AuthUserUserIdVerifyGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/api/v1/auth/user/{user_id}/verify';
};

export type VerifyAccountApiV1AuthUserUserIdVerifyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type VerifyAccountApiV1AuthUserUserIdVerifyGetError = VerifyAccountApiV1AuthUserUserIdVerifyGetErrors[keyof VerifyAccountApiV1AuthUserUserIdVerifyGetErrors];

export type VerifyAccountApiV1AuthUserUserIdVerifyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConfirmPasswordSendCodeApiV1AuthUserUserIdPasswordResetSendCodeGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/user/{user_id}/password-reset/send-code';
};

export type ConfirmPasswordSendCodeApiV1AuthUserUserIdPasswordResetSendCodeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type ConfirmPasswordSendCodeApiV1AuthUserUserIdPasswordResetSendCodeGetError = ConfirmPasswordSendCodeApiV1AuthUserUserIdPasswordResetSendCodeGetErrors[keyof ConfirmPasswordSendCodeApiV1AuthUserUserIdPasswordResetSendCodeGetErrors];

export type ConfirmPasswordSendCodeApiV1AuthUserUserIdPasswordResetSendCodeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConfirmPasswordResetApiV1AuthUserUserIdPasswordResetConfirmPostData = {
    body: ChangePasswordDataWritable;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/auth/user/{user_id}/password-reset/confirm';
};

export type ConfirmPasswordResetApiV1AuthUserUserIdPasswordResetConfirmPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type ConfirmPasswordResetApiV1AuthUserUserIdPasswordResetConfirmPostError = ConfirmPasswordResetApiV1AuthUserUserIdPasswordResetConfirmPostErrors[keyof ConfirmPasswordResetApiV1AuthUserUserIdPasswordResetConfirmPostErrors];

export type ConfirmPasswordResetApiV1AuthUserUserIdPasswordResetConfirmPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPermissionsApiV1PermissionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Subject
         */
        subject?: string | null;
        /**
         * Action
         */
        action?: string | null;
    };
    url: '/api/v1/permissions/';
};

export type GetPermissionsApiV1PermissionsGetErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type GetPermissionsApiV1PermissionsGetError = GetPermissionsApiV1PermissionsGetErrors[keyof GetPermissionsApiV1PermissionsGetErrors];

export type GetPermissionsApiV1PermissionsGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponsePermissionPublic;
};

export type GetPermissionsApiV1PermissionsGetResponse = GetPermissionsApiV1PermissionsGetResponses[keyof GetPermissionsApiV1PermissionsGetResponses];

export type CreatePermissionApiV1PermissionsPostData = {
    body: PermissionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/permissions/';
};

export type CreatePermissionApiV1PermissionsPostErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type CreatePermissionApiV1PermissionsPostError = CreatePermissionApiV1PermissionsPostErrors[keyof CreatePermissionApiV1PermissionsPostErrors];

export type CreatePermissionApiV1PermissionsPostResponses = {
    /**
     * Response Create Permission Api V1 Permissions  Post
     *
     * Successful Response
     */
    200: PermissionPublic | null;
};

export type CreatePermissionApiV1PermissionsPostResponse = CreatePermissionApiV1PermissionsPostResponses[keyof CreatePermissionApiV1PermissionsPostResponses];

export type GetRolesApiV1RolesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Name
         */
        name?: string | null;
    };
    url: '/api/v1/roles/';
};

export type GetRolesApiV1RolesGetErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type GetRolesApiV1RolesGetError = GetRolesApiV1RolesGetErrors[keyof GetRolesApiV1RolesGetErrors];

export type GetRolesApiV1RolesGetResponses = {
    /**
     * Successful Response
     */
    200: ListResponseRolePublic;
};

export type GetRolesApiV1RolesGetResponse = GetRolesApiV1RolesGetResponses[keyof GetRolesApiV1RolesGetResponses];

export type CreateRoleApiV1RolesPostData = {
    body: RoleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/roles/';
};

export type CreateRoleApiV1RolesPostErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedErrorSchema;
    /**
     * Forbidden
     */
    403: ForbiddenErrorSchema;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: InternalServerErrorSchema;
};

export type CreateRoleApiV1RolesPostError = CreateRoleApiV1RolesPostErrors[keyof CreateRoleApiV1RolesPostErrors];

export type CreateRoleApiV1RolesPostResponses = {
    /**
     * Response Create Role Api V1 Roles  Post
     *
     * Successful Response
     */
    200: RolePublic | null;
};

export type CreateRoleApiV1RolesPostResponse = CreateRoleApiV1RolesPostResponses[keyof CreateRoleApiV1RolesPostResponses];
