name: Init VM

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: FastAPI-Practics/frontend/.github/actions/ansible-setup@deploy
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_B64 }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        vm_host: ${{ secrets.VM_HOST }}
        vm_user: ${{ secrets.VM_USER }}

    - name: Setup VM
      run: |
        cd ansible
        ansible-playbook \
          -i inventory.ini \
          playbooks/init-vm-playbook.yaml
      env:
        ANSIBLE_HOST_KEY_CHECKING: "false"
        ANSIBLE_FORCE_COLOR: "true"
    
    - name: Cleanup Workspace
      if: always()
      run: |
        rm -rf ~/.ssh/
