name: Run tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
    - name: Install dependencies
      run: |
        cd app
        echo "Install deps"
        npm i
    
    - name: Run tests
      run: |
        cd app
        npx vitest --coverage.enabled true

    - name: 'Report Coverage'
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
      with:
        working-directory: ./app